services:
    postgres:
        image: postgres
        container_name: postgres
        env_file:
            - ./django_core/.env

        expose:
            - 5432

        ports:
            - 5442:5432

        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql/data
