# Generated by Django 5.0.4 on 2025-04-27 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateTimeField(verbose_name="Reservation end date"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.room",
                verbose_name="reserved room",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateTimeField(verbose_name="Reservation start date"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Guest",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveSmallIntegerField(verbose_name="Guest capacity"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Room name"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price_per_day",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Price per day"
            ),
        ),
    ]
